### ISSUE TITLE
main-0.3 scaffolds a 0.3.3-rc.0 app

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/holonix#66]
Right now, if I run:

```bash
nix run github:holochain/holonix/main-0.3#hc-scaffold web-app
```

and I add the default DNA and zomes, it scaffolds an app with this Cargo.toml:

```toml
[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
members = ["dnas/*/zomes/coordinator/*", "dnas/*/zomes/integrity/*"]
resolver = "2"

[workspace.dependencies]
hdi = "=0.4.3-rc.0"
hdk = "=0.3.3-rc.0"
serde = "1.0"
```

I've been waiting for this to be bumped to 0.3.3. Actually I think that the main branches of this repository should only have -rc versions if there is no stable version yet for that line of releases. Otherwise this causes semver incompatibility issues to anyone that's already at 0.3.x.
